### ISSUE TITLE
Installation command is not correct

### ISSUE THREAD

**Issue by pedanticantic** [cdtweb/us-states-list#2]
The command in the [readme file](https://github.com/cdtweb/us-states-list/blob/master/README.md) should be:

`composer require cdtweb/us-states-list`

It shouldn't be `composer install ...`. This is used to install/update the packages that are already in the `composer.lock` file.

This [cheat sheet](https://devhints.io/composer) explains the difference. See under _Installing dependencies_ and _Adding packages_.

**Comment by cdtweb** [comment]
Fixed with commit 54816ce

**Comment by pedanticantic** [comment]
Many thanks for fixing this!
